name: CI

on:
  push:
    branches: [ main, workflow_tests ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildRunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Start server
        run: npm start

      - name: Test sum
        run: curl -X POST https://localhost:8000/sum -H 'Content-Type: application/json' -d '[2.5, 3.0]'
  
