name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildRunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Start server
        run: npm start &

      - name: Test json
        run: curl -s -X POST http://localhost:8000/sum -H 'Content-Type: application/json' -d '[2.5, 3.0, 3.5]' | grep -q '{"status":"failure","message":"Not a json"}'

      - name: Test sum
        run: |
          curl -s -X POST http://localhost:8000/sum -H 'Content-Type: application/json' -d '[2.5, 3.0, 3.5]' | grep -q '{"status":"success","result":9}'

      - name: Test prod
        run: |
          curl -s -X POST http://localhost:8000/product -H 'Content-Type: application/json' -d '[2.5, 3.0, 3.5]' | grep -q '{"result":26.25}'
      
      - name: Test power
        run: |
          curl -s -X POST http://localhost:8000/power -H 'Content-Type: application/json' -d '[2.5, 3.0]' | grep -q '{"result":15.625}'
